### ISSUE TITLE
Add support for terraform format and validate

### ISSUE THREAD

**Issue by andyscott1986** [tfutils/tfscaffold#38]
Tools are increasing popular and we like to fail fast can you add support for "terraform fmt" and "terraform validate"

https://developer.hashicorp.com/terraform/cli/commands/fmt

https://developer.hashicorp.com/terraform/cli/commands/validate

**Comment by jack-parsons-bjss** [comment]
These commands are both implicitly supported by the 'generic action' support. No var file args will be passed as these commands do not support the passing of var files. Have you tried passing `-a fmt` or `-a validate` to tfscaffold?

**Comment by andyscott1986** [comment]
I haven't, will this do the validate for specific components?

**Comment by jack-parsons-bjss** [comment]
Yes, all actions are performed at component level before cding back to the original execution location.

**Comment by andyscott1986** [comment]
So the same should work to use checkov, TF sec or taking shouldn't it? Any reason why they wouldn't?
